[package]
name = "initializer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json="1.0"
serde = { version = "1.0", features = ["derive"] }
actix-web = "4.3.0"
dotenv = "0.15.0"
env_logger = "0.11"
log = "0.4"
simplecrypt = "1.0.2"
