services:  
  # Bun service
  bun:
    image: kalpita888/bun:0.0.1
    container_name: my-chat-agent
    init: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - /init-params/:/init-params/
    env_file:
      - /init-params/bun/.env
