version: '3.7'

services:
  # Postgres service
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_PASSWORD: postchain
      POSTGRES_DB: postchain
      POSTGRES_USER: postchain
    init: true
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postchain -d postchain -h localhost -p 5432"]
      interval: 10s
      retries: 3
    
  # Initializer for api keys
  initializer:
    build:
      context: .
      dockerfile: Dockerfile.init
    container_name: my_key_initializer
    init: true
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash ./healthcheck.sh"]
      interval: 10s
      retries: 3

  # Chromia node service
  chr-node:
    image: kalpita888/chr-node:1.0.0
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.chr
    container_name: my-chr-node
    init: true
    network_mode: host
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      initializer:
        condition: service_healthy
  
  # Bun service
  bun:
    image: kalpita888/bun:1.0.0
    # build: 
    #   context: .
    #   dockerfile: Dockerfile.bun
    container_name: my-chat-agent
    init: true
    network_mode: host
    restart: unless-stopped
    depends_on:
      - chr-node