version: '3.7'

services:
  # # Frontend service
  # frontend:
  #   image: chromia-frontend
  #   volumes:
  #     - ./ui:/usr/share/nginx/html
  #   ports:
  #     - '80:80'
  #   networks:
  #     - app-network

  # Postgres service
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_PASSWORD: postchain
      POSTGRES_DB: postchain
      POSTGRES_USER: postchain
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - app-network

  # Chromia node service
  chr-node:
    image: kalpita888/chromia-node:latest
    container_name: my-chr-node
    networks:
      - app-network
    depends_on:
      - postgres
    ports:
      - '9870:9870'
      - '7750:7750'
      - '7740:7740'
      - '6060:6060'
    # healthcheck:
    #   test: ['CMD', 'pg_isready', '-h', 'postgres', '-U', 'postgres']
    #   interval: 30s
    #   retries: 5
    volumes:
      - chromia_node:/app/
  
#  # terminal over http
#   terminal:
#     build: 
#       context: .
#       dockerfile: Dockerfile.terminal
#     container_name: chromia-terminal-service
#     environment:
#       - XAI_API_KEY=${XAI_API_KEY}
#       - CHR_NODE_API_URL=http://localhost:9870
#     depends_on:
#       - chr-node
#     networks:
#       - app-network
#     ports:
#       - 6060:6060

# Volumes and networks
volumes:
  postgres_data: 
  chromia_node:

networks:
  app-network:
    driver: bridge
