FROM alpine:latest
WORKDIR /usr/src/app

# install dependency tools
RUN apk add --no-cache musl-dev

COPY initializer-app ./
RUN chmod +x initializer-app

COPY healthCheck.sh ./
RUN chmod +x healthCheck.sh

RUN ls

EXPOSE 3030

ENTRYPOINT ["./initializer-app"]
CMD [ "bash", "healthCheck.sh" ]