version: '3.7'

services:
  # Postgres service
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_PASSWORD: postchain
      POSTGRES_DB: postchain
      POSTGRES_USER: postchain
    init: true
    network_mode: host
    restart: unless-stopped
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
    #   - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postchain -d postchain -h localhost-p 5432"]
      interval: 10s
      retries: 3
    # networks:
    #   - app-network

  # Chromia node service
  chr-node:
    # image: kalpita888/chromia-node:1.0.0
    image: kalpita888/chromia-node:0.1.0
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    container_name: my-chr-node
    # networks:
    #   - app-network
    init: true
    network_mode: host
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    # ports:
    #   - '9870:9870'
    #   - '7750:7750'
    #   - '7740:7740'
    #   - '6060:6060'
    # volumes:
    #   - chromia_node:/app/

# # Volumes and networks
# volumes:
#   postgres_data: 
#   chromia_node:

# networks:
#   app-network:
#     driver: bridge
