services:  
  # Bun service
  bun:
    image: kalpita888/bun_arm64:0.0.1                               # For arm64 system use kalpita888/bun_arm64:0.0.1 and for amd64 system use kalpita888/bun:0.0.1
    container_name: my-chat-agent
    init: true
    network_mode: host
    restart: unless-stopped
    # Local testing
    env_file:
      - ./.env
    # Production
    # volumes:
    #   - /init-params/:/init-params/
    # env_file:
    #   - /init-params/bun/.env
