services:
  # Postgres service
  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_PASSWORD: postchain
      POSTGRES_DB: postchain
      POSTGRES_USER: postchain
    init: true
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postchain -d postchain -h localhost -p 5432"]
      interval: 10s
      retries: 3

  # Chromia node service
  chr-node:
    image: kalpita888/chomia-node:1.0.0            # For arm64 system use kalpita888/chomia-node_arm64:1.0.0
    container_name: my-chr-node
    init: true
    network_mode: host
    restart: unless-stopped
    depends_on:
      - postgres
  
  # Bun service
  bun:
    image: kalpita888/bun:1.0.0           # For arm64 system use kalpita888/bun_arm64:1.0.0
    container_name: my-chat-agent
    init: true
    network_mode: host
    restart: unless-stopped
    environment:
      - XAI_API_KEY=${XAI_API_KEY}
    depends_on:
      - chr-node