FROM alpine:latest
WORKDIR /usr/src/app

# install dependency tools
RUN apk add --no-cache musl-dev

COPY initializer-app ./
RUN chmod +x initializer-app

RUN ls

EXPOSE 3030

CMD ["./initializer-app"]