FROM rust:alpine as builder
WORKDIR /usr/src/app
COPY ./initializer .
RUN apk add musl-dev
RUN cargo build --release

FROM alpine
COPY --from=builder /usr/src/app/target/release/initializer /usr/local/bin/initializer
CMD ["initializer"]